import {
  UIBuilderIconAlignXCenter,
  UIBuilderIconAlignXEnd,
  UIBuilderIconAlignXSpaceAround,
  UIBuilderIconAlignXSpaceBetween,
  UIBuilderIconAlignXStart,
  UIBuilderIconAlignXStretch,
  UIBuilderIconAlignYBaseline,
  UIBuilderIconAlignYCenter,
  UIBuilderIconAlignYEnd,
  UIBuilderIconAlignYStart,
  UIBuilderIconAlignYStretch,
  UIBuilderIconArrowDown,
  UIBuilderIconArrowForward,
  UIBuilderIconTree,
  UIBuilderIconUndo,
  UIBuilderIconRedo,
  UIBuilderIconTrash,
  UIBuilderIconGrip,
  UIBuilderIconEye,
  UIBuilderIconEyeSlash
} from "./svg-icons";

export const iconsLibrary = [
  UIBuilderIconAlignXCenter,
  UIBuilderIconAlignXEnd,
  UIBuilderIconAlignXSpaceAround,
  UIBuilderIconAlignXSpaceBetween,
  UIBuilderIconAlignXStart,
  UIBuilderIconAlignXStretch,
  UIBuilderIconAlignYBaseline,
  UIBuilderIconAlignYCenter,
  UIBuilderIconAlignYEnd,
  UIBuilderIconAlignYStart,
  UIBuilderIconAlignYStretch,
  UIBuilderIconArrowDown,
  UIBuilderIconArrowForward,
  UIBuilderIconTree,
  UIBuilderIconUndo,
  UIBuilderIconRedo,
  UIBuilderIconTrash,
  UIBuilderIconGrip,
  UIBuilderIconEye,
  UIBuilderIconEyeSlash
]