/* 🤖 this file was generated by svg-to-ts */
export const UIBuilderIconAlignXCenter: UIBuilderIcon = {
  name: 'align_x_center',
  data: `<svg viewBox="0 0 16 16"><rect y="1" width="1.5" height="14" rx=".75" opacity=".7"/><rect x="14.5" y="1" width="1.5" height="14" rx=".75" opacity=".7"/><rect x="4" y="4" width="4" height="8" rx="1"/><rect x="8.5" y="4" width="4" height="8" rx="1"/></svg>`
};
export const UIBuilderIconAlignXEnd: UIBuilderIcon = {
  name: 'align_x_end',
  data: `<svg id="sprite-align-x-end" viewBox="0 0 16 16"><rect opacity=".7" x="14.5" y="1" width="1.5" height="14" rx=".75"/><rect opacity=".7" y="1" width="1.5" height="14" rx=".75"/><rect x="5" y="4" width="4" height="8" rx="1"/><rect x="9.5" y="4" width="4" height="8" rx="1"/></svg>`
};
export const UIBuilderIconAlignXSpaceAround: UIBuilderIcon = {
  name: 'align_x_space_around',
  data: `<svg id="sprite-align-x-space-around" viewBox="0 0 16 16"><rect opacity=".7" x="14.5" y="1" width="1.5" height="14" rx=".75"/><rect opacity=".7" y="1" width="1.5" height="14" rx=".75"/><rect x="3" y="4" width="4" height="8" rx="1"/><rect x="9" y="4" width="4" height="8" rx="1"/></svg>`
};
export const UIBuilderIconAlignXSpaceBetween: UIBuilderIcon = {
  name: 'align_x_space_between',
  data: `<svg id="sprite-align-x-space-between" viewBox="0 0 16 16"><rect opacity=".7" x="14.5" y="1" width="1.5" height="14" rx=".75"/><rect opacity=".7" y="1" width="1.5" height="14" rx=".75"/><rect x="2" y="4" width="4" height="8" rx="1"/><rect x="10" y="4" width="4" height="8" rx="1"/></svg>`
};
export const UIBuilderIconAlignXStart: UIBuilderIcon = {
  name: 'align_x_start',
  data: `<svg viewBox="0 0 16 16"><rect x="2.5" y="4" width="4" height="8" rx="1"/><rect x="7" y="4" width="4" height="8" rx="1"/><rect opacity=".7" y="1" width="1.5" height="14" rx=".75"/><rect opacity=".7" x="14.5" y="1" width="1.5" height="14" rx=".75"/></svg>`
};
export const UIBuilderIconAlignXStretch: UIBuilderIcon = {
  name: 'align_x_stretch',
  data: `<svg id="sprite-align-x-stretch" viewBox="0 0 16 16"><rect x="3" y="12.5" width="4" height="10" rx="1" transform="rotate(-90 3 12.5)"/><rect x="3" y="7.5" width="4" height="10" rx="1" transform="rotate(-90 3 7.5)"/><rect opacity=".7" x=".5" y="15" width="14" height="1.5" rx=".75" transform="rotate(-90 .5 15)"/><rect opacity=".7" x="14" y="15" width="14" height="1.5" rx=".75" transform="rotate(-90 14 15)"/></svg>`
};
export const UIBuilderIconAlignYBaseline: UIBuilderIcon = {
  name: 'align_y_baseline',
  data: `<svg id="sprite-align-y-baseline" viewBox="0 0 16 16"><rect opacity=".7" x="1" y="7" width="14" height="1.5" rx=".75"/><rect x="3.5" y="3" width="4" height="10" rx="1"/><rect x="8.5" y="3" width="4" height="8" rx="1"/></svg>`
};
export const UIBuilderIconAlignYCenter: UIBuilderIcon = {
  name: 'align_y_center',
  data: `<svg id="sprite-align-y-center" viewBox="0 0 16 16"><rect x="4" y="1" width="4" height="14" rx="1"/><rect x="9" y="4" width="4" height="8" rx="1"/><rect opacity=".7" x="1" y="7" width="14" height="1.5" rx=".75"/></svg>`
};
export const UIBuilderIconAlignYEnd: UIBuilderIcon = {
  name: 'align_y_end',
  data: `<svg id="sprite-align-y-end" viewBox="0 0 16 16"><rect x="4" y="1" width="4" height="12" rx="1"/><rect x="9" y="5" width="4" height="8" rx="1"/><rect opacity=".7" x="1" y="14" width="14" height="1.5" rx=".75"/></svg>`
};
export const UIBuilderIconAlignYStart: UIBuilderIcon = {
  name: 'align_y_start',
  data: `<svg id="sprite-align-y-start" viewBox="0 0 16 16"><rect x="3" y="3" width="4" height="12" rx="1"/><rect x="8" y="3" width="4" height="8" rx="1"/><rect opacity=".7" x="1" y=".5" width="14" height="1.5" rx=".75"/></svg>`
};
export const UIBuilderIconAlignYStretch: UIBuilderIcon = {
  name: 'align_y_stretch',
  data: `<svg id="sprite-align-y-stretch" viewBox="0 0 16 16"><rect x="3.5" y="3" width="4" height="10" rx="1"/><rect x="8.5" y="3" width="4" height="10" rx="1"/><rect opacity=".7" x="1" y=".5" width="14" height="1.5" rx=".75"/><rect opacity=".7" x="1" y="14" width="14" height="1.5" rx=".75"/></svg>`
};
export const UIBuilderIconArrowDown: UIBuilderIcon = {
  name: 'arrow_down',
  data: `<svg viewBox="0 0 18 18"><path fill-rule="evenodd" clip-rule="evenodd" d="M3.045 8.204a1.125 1.125 0 10-1.59 1.591l6.75 6.75c.439.44 1.151.44 1.59 0l6.75-6.75a1.125 1.125 0 00-1.59-1.59l-4.83 4.829V2.125a1 1 0 00-1-1h-.25a1 1 0 00-1 1v10.909l-4.83-4.83z"/></svg>`
};
export const UIBuilderIconArrowForward: UIBuilderIcon = {
  name: 'arrow_forward',
  data: `<svg viewBox="0 0 18 18"><path fill-rule="evenodd" clip-rule="evenodd" d="M8.204 14.954a1.125 1.125 0 001.591 1.591l6.75-6.75c.44-.439.44-1.151 0-1.59l-6.75-6.75a1.125 1.125 0 00-1.59 1.59l4.829 4.83H2.125a1 1 0 00-1 1v.25a1 1 0 001 1h10.909l-4.83 4.83z"/></svg>`
};
export const UIBuilderIconTree: UIBuilderIcon = {
  name: 'tree',
  data: `<svg viewBox="0 0 576 512"><path d="M544 32h-112l-32-32H320c-17.62 0-32 14.38-32 32v160c0 17.62 14.38 32 32 32h224c17.62 0 32-14.38 32-32V64C576 46.38 561.6 32 544 32zM544 320h-112l-32-32H320c-17.62 0-32 14.38-32 32v160c0 17.62 14.38 32 32 32h224c17.62 0 32-14.38 32-32v-128C576 334.4 561.6 320 544 320zM64 16C64 7.125 56.88 0 48 0h-32C7.125 0 0 7.125 0 16V416c0 17.62 14.38 32 32 32h224v-64H64V160h192V96H64V16z"/></svg>`
}
export type myIcons =
  | 'align_x_center'
  | 'align_x_end'
  | 'align_x_space_around'
  | 'align_x_space_between'
  | 'align_x_start'
  | 'align_x_stretch'
  | 'align_y_baseline'
  | 'align_y_center'
  | 'align_y_end'
  | 'align_y_start'
  | 'align_y_stretch'
  | 'arrow_down'
  | 'arrow_forward'
  | 'tree';
export interface UIBuilderIcon {
  name: myIcons;
  data: string;
}
export type UIBuilderIconNameSubset<
  T extends Readonly<UIBuilderIcon[]>
> = T[number]['name'];
