/* 🤖 this file was generated by svg-to-ts */
export const UIBuilderIconAlignXCenter: UIBuilderIcon = {
  name: 'align_x_center',
  data: `<svg viewBox="0 0 16 16"><rect y="1" width="1.5" height="14" rx=".75" opacity=".7"/><rect x="14.5" y="1" width="1.5" height="14" rx=".75" opacity=".7"/><rect x="4" y="4" width="4" height="8" rx="1"/><rect x="8.5" y="4" width="4" height="8" rx="1"/></svg>`
};
export const UIBuilderIconAlignXEnd: UIBuilderIcon = {
  name: 'align_x_end',
  data: `<svg id="sprite-align-x-end" viewBox="0 0 16 16"><rect opacity=".7" x="14.5" y="1" width="1.5" height="14" rx=".75"/><rect opacity=".7" y="1" width="1.5" height="14" rx=".75"/><rect x="5" y="4" width="4" height="8" rx="1"/><rect x="9.5" y="4" width="4" height="8" rx="1"/></svg>`
};
export const UIBuilderIconAlignXSpaceAround: UIBuilderIcon = {
  name: 'align_x_space_around',
  data: `<svg id="sprite-align-x-space-around" viewBox="0 0 16 16"><rect opacity=".7" x="14.5" y="1" width="1.5" height="14" rx=".75"/><rect opacity=".7" y="1" width="1.5" height="14" rx=".75"/><rect x="3" y="4" width="4" height="8" rx="1"/><rect x="9" y="4" width="4" height="8" rx="1"/></svg>`
};
export const UIBuilderIconAlignXSpaceBetween: UIBuilderIcon = {
  name: 'align_x_space_between',
  data: `<svg id="sprite-align-x-space-between" viewBox="0 0 16 16"><rect opacity=".7" x="14.5" y="1" width="1.5" height="14" rx=".75"/><rect opacity=".7" y="1" width="1.5" height="14" rx=".75"/><rect x="2" y="4" width="4" height="8" rx="1"/><rect x="10" y="4" width="4" height="8" rx="1"/></svg>`
};
export const UIBuilderIconAlignXStart: UIBuilderIcon = {
  name: 'align_x_start',
  data: `<svg viewBox="0 0 16 16"><rect x="2.5" y="4" width="4" height="8" rx="1"/><rect x="7" y="4" width="4" height="8" rx="1"/><rect opacity=".7" y="1" width="1.5" height="14" rx=".75"/><rect opacity=".7" x="14.5" y="1" width="1.5" height="14" rx=".75"/></svg>`
};
export const UIBuilderIconAlignXStretch: UIBuilderIcon = {
  name: 'align_x_stretch',
  data: `<svg id="sprite-align-x-stretch" viewBox="0 0 16 16"><rect x="3" y="12.5" width="4" height="10" rx="1" transform="rotate(-90 3 12.5)"/><rect x="3" y="7.5" width="4" height="10" rx="1" transform="rotate(-90 3 7.5)"/><rect opacity=".7" x=".5" y="15" width="14" height="1.5" rx=".75" transform="rotate(-90 .5 15)"/><rect opacity=".7" x="14" y="15" width="14" height="1.5" rx=".75" transform="rotate(-90 14 15)"/></svg>`
};
export const UIBuilderIconAlignYBaseline: UIBuilderIcon = {
  name: 'align_y_baseline',
  data: `<svg id="sprite-align-y-baseline" viewBox="0 0 16 16"><rect opacity=".7" x="1" y="7" width="14" height="1.5" rx=".75"/><rect x="3.5" y="3" width="4" height="10" rx="1"/><rect x="8.5" y="3" width="4" height="8" rx="1"/></svg>`
};
export const UIBuilderIconAlignYCenter: UIBuilderIcon = {
  name: 'align_y_center',
  data: `<svg id="sprite-align-y-center" viewBox="0 0 16 16"><rect x="4" y="1" width="4" height="14" rx="1"/><rect x="9" y="4" width="4" height="8" rx="1"/><rect opacity=".7" x="1" y="7" width="14" height="1.5" rx=".75"/></svg>`
};
export const UIBuilderIconAlignYEnd: UIBuilderIcon = {
  name: 'align_y_end',
  data: `<svg id="sprite-align-y-end" viewBox="0 0 16 16"><rect x="4" y="1" width="4" height="12" rx="1"/><rect x="9" y="5" width="4" height="8" rx="1"/><rect opacity=".7" x="1" y="14" width="14" height="1.5" rx=".75"/></svg>`
};
export const UIBuilderIconAlignYStart: UIBuilderIcon = {
  name: 'align_y_start',
  data: `<svg id="sprite-align-y-start" viewBox="0 0 16 16"><rect x="3" y="3" width="4" height="12" rx="1"/><rect x="8" y="3" width="4" height="8" rx="1"/><rect opacity=".7" x="1" y=".5" width="14" height="1.5" rx=".75"/></svg>`
};
export const UIBuilderIconAlignYStretch: UIBuilderIcon = {
  name: 'align_y_stretch',
  data: `<svg id="sprite-align-y-stretch" viewBox="0 0 16 16"><rect x="3.5" y="3" width="4" height="10" rx="1"/><rect x="8.5" y="3" width="4" height="10" rx="1"/><rect opacity=".7" x="1" y=".5" width="14" height="1.5" rx=".75"/><rect opacity=".7" x="1" y="14" width="14" height="1.5" rx=".75"/></svg>`
};
export const UIBuilderIconArrowDown: UIBuilderIcon = {
  name: 'arrow_down',
  data: `<svg viewBox="0 0 18 18"><path fill-rule="evenodd" clip-rule="evenodd" d="M3.045 8.204a1.125 1.125 0 10-1.59 1.591l6.75 6.75c.439.44 1.151.44 1.59 0l6.75-6.75a1.125 1.125 0 00-1.59-1.59l-4.83 4.829V2.125a1 1 0 00-1-1h-.25a1 1 0 00-1 1v10.909l-4.83-4.83z"/></svg>`
};
export const UIBuilderIconArrowForward: UIBuilderIcon = {
  name: 'arrow_forward',
  data: `<svg viewBox="0 0 18 18"><path fill-rule="evenodd" clip-rule="evenodd" d="M8.204 14.954a1.125 1.125 0 001.591 1.591l6.75-6.75c.44-.439.44-1.151 0-1.59l-6.75-6.75a1.125 1.125 0 00-1.59 1.59l4.829 4.83H2.125a1 1 0 00-1 1v.25a1 1 0 001 1h10.909l-4.83 4.83z"/></svg>`
};
export const UIBuilderIconTree: UIBuilderIcon = {
  name: 'tree',
  data: `<svg viewBox="0 0 576 512"><path d="M544 32h-112l-32-32H320c-17.62 0-32 14.38-32 32v160c0 17.62 14.38 32 32 32h224c17.62 0 32-14.38 32-32V64C576 46.38 561.6 32 544 32zM544 320h-112l-32-32H320c-17.62 0-32 14.38-32 32v160c0 17.62 14.38 32 32 32h224c17.62 0 32-14.38 32-32v-128C576 334.4 561.6 320 544 320zM64 16C64 7.125 56.88 0 48 0h-32C7.125 0 0 7.125 0 16V416c0 17.62 14.38 32 32 32h224v-64H64V160h192V96H64V16z"/></svg>`
}
export const UIBuilderIconUndo: UIBuilderIcon = {
  name: 'undo',
  data: `<svg viewBox="0 0 512 512"><path d="M480 256c0 123.4-100.5 223.9-223.9 223.9c-48.84 0-95.17-15.58-134.2-44.86c-14.12-10.59-16.97-30.66-6.375-44.81c10.59-14.12 30.62-16.94 44.81-6.375c27.84 20.91 61 31.94 95.88 31.94C344.3 415.8 416 344.1 416 256s-71.69-159.8-159.8-159.8c-37.46 0-73.09 13.49-101.3 36.64l45.12 45.14c17.01 17.02 4.955 46.1-19.1 46.1H35.17C24.58 224.1 16 215.5 16 204.9V59.04c0-24.04 29.07-36.08 46.07-19.07l47.6 47.63C149.9 52.71 201.5 32.11 256.1 32.11C379.5 32.11 480 132.6 480 256z"/></svg>`
}
export const UIBuilderIconRedo: UIBuilderIcon = {
  name: 'redo',
  data: `<svg viewBox="0 0 512 512"><path d="M468.9 32.11c13.87 0 27.18 10.77 27.18 27.04v145.9c0 10.59-8.584 19.17-19.17 19.17h-145.7c-16.28 0-27.06-13.32-27.06-27.2c0-6.634 2.461-13.4 7.96-18.9l45.12-45.14c-28.22-23.14-63.85-36.64-101.3-36.64c-88.09 0-159.8 71.69-159.8 159.8S167.8 415.9 255.9 415.9c73.14 0 89.44-38.31 115.1-38.31c18.48 0 31.97 15.04 31.97 31.96c0 35.04-81.59 70.41-147 70.41c-123.4 0-223.9-100.5-223.9-223.9S132.6 32.44 256 32.44c54.6 0 106.2 20.39 146.4 55.26l47.6-47.63C455.5 34.57 462.3 32.11 468.9 32.11z"/></svg>`
}
export type myIcons =
  | 'align_x_center'
  | 'align_x_end'
  | 'align_x_space_around'
  | 'align_x_space_between'
  | 'align_x_start'
  | 'align_x_stretch'
  | 'align_y_baseline'
  | 'align_y_center'
  | 'align_y_end'
  | 'align_y_start'
  | 'align_y_stretch'
  | 'arrow_down'
  | 'arrow_forward'
  | 'tree'
  | 'undo'
  | 'redo';
export interface UIBuilderIcon {
  name: myIcons;
  data: string;
}
export type UIBuilderIconNameSubset<
  T extends Readonly<UIBuilderIcon[]>
> = T[number]['name'];
